# Site settings
title: Fourth World Congress of Psychogeography
email: email@example.com
url: https://timwaters.github.io
description: "Fourth World Congress of Psychogeography - a festival of walking, space, place and the town of Huddersfield, West Yorkshire. Free events. 9-10 September 2016"
baseurl: ""

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Fourth World Congress of Psychogeography - Huddersfield 9-10 September 2016

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?f=tweets&q=%234wcop
  - title: facebook
    url: https://www.facebook.com/groups/HuddersfieldPsychogeographyNetwork/


# Build settings
markdown: kramdown
permalink: pretty

#Events collection

friday-events:
  - title: Psychogeography Extreme
    by: Phil Smith
    location: Heritage Quay
    time: 4pm - 5pm
    description: What is the future for psychogeography? To open the Congress, Phil Smith will outline his proposal for a state of walking that explores the frontiers of human identity, ecology and much much more. Looking at some future shifts in contemporary psychogeography, Phil proposes a walking which is both quest and architecture that produces more in the way of totalities than fragments. 
    type: Talk
    note: Free event, just turn up!
  - title: Scavenger's Hunt
    by: Sophia Emmanouil
    location: Heritage Quay and then around University Campus
    time: 5pm - 6.30pm (90 mins)
    description: Calling scavengers young and old to follow a trail around the university campus in the search of items and stories, mundane or otherwise. The findings of the explorations will be exhibited in the Instant Museum of Curiosities at Heritage Quay, so come with a playful mood and an enquiring mind.
    type: Walk
    note: Free event, just turn up!
  - title: A Walk in the Park
    by: Travis Elborough
    location: Heritage Quay
    time: 7pm - 9pm
    description: Travis Elborough talks about his new book (A Walk in the Park, just out in Penquin). It's a joyful and loving portrait of a small wonder that we may risk taking for granted and which, right now in an era of cuts, is and institution under threat. This talk is not to be missed!
    type: Talk
    note:

saturday-events:
  - title: What is Psychogeography
    by: Alex Bridger
    location: Heritage Quay
    time: 11.30am - 12pm (30 mins)
    description: Is it simply about walking, that brings in psychology and geography or is it an artistic, literary or political practice? Psychogeography can be all of these and can be drawn on by anyone to take a fresh look at many aspects of living, working and leisure. 
    type: Talk 
    note:
  - title: The Northern Powerhouse in a post-Brexit world
    by: Alex Bridger
    location: Start at Heritage Quay and then around town
    time: 12pm - 2pm (75 mins)
    description: Alex Bridger leads a walk around the town centre thinking about consumerism, surveillance, security and ownership before returning to Heritage Quay to create DIY maps showing just where the power lies.  
    type: Walk
    note: Free walk but please <a href="https://www.eventbrite.com/e/the-northern-powerhouse-in-a-post-brexit-world-tickets-26827973190">sign up on Eventbrite for a ticket</a> as space is limited.  
  - title: Walking over Mines
    by: Tim Waters
    location: Start at Heritage Quay
    time: 12pm - 2pm (105 mins)
    description: Tim will lead you over the labyrinth of concealed and invisible coal workings that lie just beneath the surface of Huddersfield town centre. His psychogeographic insights will give you a whole new view on the stuff beneath our streets.
    type: Walk
    note:           
  - title: Ghost Trails of Diaspora
    by: Phil Wood
    location: Heritage Quay
    time: 2pm - 3pm 
    description: Phil Wood draws upon a deep knowledge of the migrant groups which have settled in Huddersfield as well as many of their places of origin. He will describe remarkable journeys and uncovers some strange and surprising concurrences whilst walking, one foot in Huddersfield and one elsewhere.
    type: Walk
    note:
  - title: The Studentification of Urban Space
    by: Tina Richardson
    location: Heritage Quay
    time: 3pm - 4pm
    description: Tina Richardson will discuss the rise of private halls of residences in university towns and cities. Looking at examples from Huddersfield and Leeds, Tina will show how these forms of accommodation, which may seem innocuous, may have other impacts.
    type: Talk
    note:
  - title: Getting Lost on Purpose
    by: Tim Waters
    location: Start at Heritage Quay and then wherever 
    time: 4pm - 6pm (105 mins)
    description: Participants will devise unconventional rules and methods for walking (such as a flip of a coin or dice or following odd patterns), and then put them into practice around town. By getting lost on purpose we move across the streets in a way we haven't done before which can lead us to new insights about how we use the spaces and places we are in. We may get lost so let's see where you end up!
    type: Walk
    note: Free walk but please <a href="https://www.eventbrite.com/e/walk-getting-lost-on-purpose-tickets-26968189581  ">sign up on Eventbrite for a ticket</a> as space is limited.       
  - title: Any Other Business
    by: All
    location: Heritage Quay 
    time: 6pm (15 mins)
    description: Let's all meet back from our walks to take part in the Motion of No Confidence and formal Dis-Assembly of the 4th World Congress of Psychogeography, including any expulsions, unresignations and votes. 
    type: Panel
    note:        
        
other-events:
  - title:
    by: 
    location: 
    time: 
    description: 
    type: 
    note:  
    
bios:
  - name: Phil Smith
    description: Phil Smith (aka "Crab Man", "Mytho") is a performance maker, writer and ambulatory researcher.  He specialises in creating performances related to walking, site-specificity, mythogeographies and counter-tourism.  He writes and performs "mis-guided tours".  Phil's publications include A Footbook of Zombie Walking, Walking's New Movement, Enchanted Things, and Mythogeography.  He is also a playwright, with over 120 of his plays and adaptations having been produced and toured globally.  He is an Associate Professor (Reader) at Plymouth University
    image: phil-s-twitter.jpg
  - name: Sophia Emmanouil
    description: Sophia designs and facilitates a range of creative projects in partnership with schools, health and arts organisations, community groups and other voluntary and community collectives. Sophia's research, which incorporates Situationist approaches to space, place and mapping, transgresses architecture, design and education, and takes experimental approaches to sustainability and psychogeography.  Her work also considers art, design and architecture from a public engagement perspective. Sophia is also part of a collective of radical researchers from the University of East London and the University of Huddersfield looking at ways of producing critical knowledge through walking, mapping and arts.
    image: sophia-uni.jpg
  - name: Travis Elborough
    description: Travis Elborough has been a freelance writer, author and cultural commentator for more than a decade now. His books include The Bus We Loved a history of the Routemaster bus; The Long Player Goodbye, a hymn to vinyl records; Wish You Were Here, a survey of the British beside the seaside and London Bridge in America; The Tall Story of a Transatlantic Crossing. The most recent book <a href="https://www.penguin.co.uk/books/1098877/a-walk-in-the-park/">A Walk in the Park; The Life and Times of a People's Institution</a> was published by Jonathan Cape in June 2016 and described as "a fascinating, informative, revelatory book" by William Boyd in <a href="https://www.theguardian.com/books/2016/jun/18/a-walk-in-the-park-the-life-and-times-of-a-peoples-institution-travis-elborough-review">The Guardian.</a>
    image: travis-blog.png
  - name: Alex Bridger
    description: 'Alex Bridger works at the University of Huddersfield teaching critical and community psychology and approaches to research including psychogeography and the analysis of media texts and political rhetoric. He also involved with chairing the Huddersfield Psychogeographical Network and is currently writing a book titled Psychogeography and Psychology. You can contact him and/or find out more about his work at <br /> Email: <a href="mailto:a.j.bridger@hud.ac.uk">a.j.bridger@hud.ac.uk</a>, <a href="https://www.hud.ac.uk/ourstaff/profile/index.php?staffid=483">University Staff profile</a> <br /> Facebook: <a href="https://www.facebook.com/groups/HuddersfieldPsychogeographyNetwork/">Huddersfield Psychogeographical Network</a><br /> Blog: <a href="https://notanotherpsychogeographyblog.wordpress.com">https://notanotherpsychogeographyblog.wordpress.com</a> '
    image: alex-google.jpg
  - name: Tim Waters    
    description: Tim is a psychogeographer, digital humanities enthusiast and freelance geographer. He likes historical maps. He's worked with the likes of the New York Public Library, the Library of Congress and the Wikimedia Foundation. He has been part of Leeds Psychogeography Group and organises the annual <a href="http://terminaliafestival.org">Terminalia Festival</a> of Psychogeography. He's also responsible for this website.
    image: tim-sz.png
  - name: Phil Wood
    description: 'Phil Wood is the Urban Therapist, an intercultural path-beater scavenging the discarded edgelands of our settlements and memories; confronting us with our hubristic follies and rekindling our capacity for compassion and community. He works and walks all over the world but has never really left Huddersfield. <br /> Web: <a href="http://philwood.eu/">http://philwood.eu/</a> <br />Blog: <a href="http://subversiveurbanism.tumblr.com/">http://subversiveurbanism.tumblr.com</a> <br /> <a href="https://twitter.com/PhilWood11">@PhilWood11 </a> '
    image: phil-w.jpeg
  - name: Tina Richardson
    description: 'Tina Richardson specialises in the field of urban cultural studies. Having received her PhD at the University of Leeds in 2014 she is now an independent scholar, working as an editor-writer, guest lecturer and consultant. Tinaâ€™s latest edited volume has been published by Rowman and Littlefield International : <a href="http://www.rowmaninternational.com/books/walking-inside-out">Walking Inside Out - Contemporary British Psychogeography (2015)</a>. From a cultural theory and psychogeography background, Tina specialises in - identity and place, the application of poststructural theory to space, and the appearance of urban space under neoliberalism. <br /> Schizocartography Website: <a href="http://www.schizocartography.org/">http://www.schizocartography.org/</a> <br /> Blog: <a href="http://particulations.blogspot.co.uk/">http://particulations.blogspot.co.uk/</a><br /> Twitter : <a href="https://twitter.com/concretepost">@concretepost</a>'
    image: tina-sz.png
  - name: David Smith
    description: David the Participation and Engagement Officer at Heritage Quay. He's the host of the Congress and responsible for it all coming together!
    image: david-smith.jpg
  - name: The Bored in the City Collective
    description: The bored in the city collective are a motley group of psychogeographers, artists, writers and poets that reside in the Manchester region. Over the past 15 years they have produced numerous situationist inspired leaflets, zines, comic books and DIY maps in relation to reflecting on the capitalist gentrification of Manchester city centre, the war on terror and a critique of spectacular society. They have been involved in numerous stunts and interventions and their greatest achievement has been the levitation of both bus stations in Manchester June 2008. You can contact them at <a href="mailto:Boredinthecity@hotmail.co.uk">Boredinthecity@hotmail.co.uk</a>
    image:

